source/backend/functions/cost-parser/costParser.js

No issue, just cleaning the code ;) 
Feels self-explanatory, there are misspelled words in variable names.

Fix typos in costParser.js

---

.github/ISSUE_TEMPLATE/bug_report.md

NA
Add a link to the discovery process debugging guide from the bug report issue template

Add link to discovery process debugging guide

---

source/frontend/package-lock.json
source/frontend/package.json

There's a security issue with this library so I've ran `npm audit` to fix it.

update object-path dependency

---

deployment/perspective-setup.yaml

Clarified english in setup e-mail to contain contact for this deployment of AWS Perspective and append proper e-mail domain name to the AWS solution contact for Perspective.
Clarified english in setup e-mail to contain contact for this deployment of AWS Perspective and append proper e-mail domain name to the AWS solution contact for Perspective.

Update perspective-setup.yaml to clarify e-mail authenticity

---

README.md

#84 
Add instructions for running the Perspective web UI locally.
*Testing*
I have tested these changes by executing the steps myself.

Add instructions for running Web UI locally

---

deployment/perspective-setup.yaml
source/backend/functions/setup/cfn-handler.js
source/cfn/templates/zoom-elasticsearch.yaml
source/cfn/templates/zoom-main.yaml

*Issue:*
#53 
Adds `ElasticsearchInstanceType` parameter

Add ElasticsearchInstanceType parameter

---

source/frontend/package-lock.json

Patch react-scripts dependency.

Patch is-svg dependency

---

source/backend/discovery/package-lock.json
source/backend/functions/api/package-lock.json
source/backend/functions/cost-parser/package-lock.json
source/backend/functions/search/package-lock.json
source/backend/functions/settings/package-lock.json
source/backend/functions/setup/package-lock.json
source/backend/functions/setup/package.json
source/frontend/package-lock.json

Fix security issues in node.js services.

patch dependencies for security issues

---

source/frontend/package-lock.json
source/frontend/package.json

Fix issue relate to Handlebars dependency in amplify-graphql-docs-generator.

patch amplify-graphql-docs-generator dependency

---

.gitignore
source/backend/functions/lambda-layers/boto_utils/python/boto_utils.py
source/backend/functions/lambda-layers/decorators/python/decorators.py

closes https://github.com/awslabs/aws-perspective/issues/64
Adding the missing .py files into the python directories. 

adding missing .py files for lambda-layers

---

CHANGELOG.md
deployment/perspective-setup.yaml
source/backend/discovery/package-lock.json
source/backend/discovery/package.json
source/backend/discovery/src/discovery/discovery-service.js
source/backend/functions/api/package-lock.json
source/backend/functions/api/package.json
source/backend/functions/cost-parser/package-lock.json
source/backend/functions/cost-parser/package.json
source/backend/functions/cur-setup/package-lock.json
source/backend/functions/cur-setup/package.json
source/backend/functions/graph-api/package-lock.json
source/backend/functions/search/package-lock.json
source/backend/functions/search/package.json
source/backend/functions/settings/package-lock.json
source/backend/functions/settings/package.json
source/backend/functions/setup/package-lock.json
source/backend/functions/setup/package.json
source/cfn/templates/perspective-cloudfront.yaml
source/frontend/src/Main.js
source/frontend/src/Utils/Dictionaries/service-names.js
source/frontend/src/components/Drawer/Costs/QueryBuilder/CostQuery.js
source/frontend/src/components/Drawer/Costs/QueryBuilder/CostQueryForm.js
source/frontend/src/components/Drawer/Costs/QueryBuilder/CostQueryResults.js
source/frontend/src/components/Drawer/Costs/Report/CostForm.js
source/frontend/src/components/Drawer/Costs/Report/CostOverview.js
source/frontend/src/components/Drawer/PersistentDrawer/Costs/CostContainer.js
source/frontend/src/components/Drawer/Settings/Costs/CostSettings.js

v1.1.2 release

---

README.md

Fixing version number in README.

Fixing README title with correct version number

---

source/backend/functions/cur-setup/package-lock.json
source/backend/functions/cur-setup/package.json

Fix to update mocha devDependency vulnerability

security fixes

---

source/backend/discovery/package-lock.json
source/backend/discovery/package.json
source/backend/discovery/src/discovery/discovery.js

Upgrade the AWS credentials library to stop using the beta version.

fix vulnerability in aws credentials package

---

.idea/.gitignore
.idea/modules.xml
.idea/vcs.xml
CHANGELOG.md
README.md
docs/modules/ROOT/nav.adoc
docs/modules/ROOT/pages/cost-optimization.adoc
source/backend/discovery/src/lib/additionalResources/index.js
source/backend/discovery/src/lib/aggregator/getAllConfigResources.js
source/backend/discovery/src/lib/apiClient/index.js
source/backend/discovery/src/lib/utils.js
source/backend/functions/cost-parser/package-lock.json
source/backend/functions/cur-setup/package-lock.json
source/backend/functions/graph-api/package-lock.json
source/backend/functions/lambda-layers/decorators/requirements.txt
source/backend/functions/search-api/package-lock.json
source/backend/functions/settings/src/index.js
source/backend/functions/settings/test/index.js
source/cfn/templates/gremlin-resolvers.template
source/cfn/templates/main.template
source/cfn/templates/neptune.template
source/cfn/templates/settings-resolvers.template
source/frontend/package-lock.json
source/frontend/package.json

update to version v2.0.1

---

docs/modules/ROOT/nav.adoc
docs/modules/ROOT/pages/scaling-the-discovery-process.adoc

This pull requests adds documentation for scaling the discovery process to ingest tens to hundreds of thousands of resources.

add docs for scaling the discovery process

---

.github/workflows/pull-request-workflow.yml

This PR ensures the unit tests run on each pull request.

run unit tests on each PR

---

.github/workflows/pull-request-workflow.yml

The PR adds an action to install Ruby and `cfn-nag` to allow the tool to be ran against the project's CloudFormation templates on every PR.

Run cfn_nag on pull requests

---

source/cfn/templates/discovery-crawler.template

Issue #, if available: Resolves #369
Changes the discovery process to use Fargate Spot.

Use Fargate Spot for discovery process

---

source/cfn/templates/app-registry.template
source/cfn/templates/main.template

Closes #352. This PR integrates the solution with Service Catalog App Registry. This means that customers can view the Workload Discovery on AWS application in Application Manager, which is part of Systems Manager. The Application manager provides customers with an application-level view which they can use to see the costs, resources, logs associated with the AWS Solutions.

App registry integration

---

source/backend/discovery/src/lib/sdkResources/createAllBatchResources.js

This PR makes the error handling for batch adding SDK resources consistent with other parts of the code. Previously any time an error was encountered it was logged immediately. This is an issue when AWS Organizations manages account discovery as Workload Discovery may attempt to discover services not available in regions in use throughout the organization leading to very noisy logs.
We now follow the same pattern as used by our [PromisePool dependency](https://superchargejs.com/docs/3.x/promise-pool) where any errors that are encountered are saved in a set format and we log them once as a JSON attribute as part of our structured logging.
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of …

Refactor batch SDK resource discovery

---

source/frontend/package-lock.json

Reverts aws-solutions/workload-discovery-on-aws#400

Revert "Bump webpack from 5.74.0 to 5.76.1 in /source/frontend"

---

source/backend/functions/account-import-templates-api/src/global-resources.template

Added DynamoDB DescribeStream Role to template.

Added DynamoDB Streams role to template

---

debugging-flowchart.mmd

Fixes rendering issue for debugging flow chart as GitHub requires lines of text that span more than one line to have double quotes around them.

fix mermaidjs markdown for debugging flow chart

---

solution-manifest.yaml
source/sdk/js/package-lock.json
source/sdk/js/package.json

Fixes security vulneraility in `vite` subdependency of `vitest`.

update vitest to fix security vulnerability

---

CHANGELOG.md
README.md
deployment/build-open-source-dist.sh
source/backend/discovery/package-lock.json
source/backend/discovery/package.json
source/backend/functions/account-import-templates-api/package-lock.json
source/backend/functions/account-import-templates-api/package.json
source/backend/functions/cost-parser/package-lock.json
source/backend/functions/cost-parser/package.json
source/backend/functions/cur-notification/package-lock.json
source/backend/functions/cur-notification/package.json
source/backend/functions/cur-setup/package-lock.json
source/backend/functions/cur-setup/package.json
source/backend/functions/graph-api/package-lock.json
source/backend/functions/graph-api/package.json
source/backend/functions/metrics/package-lock.json
source/backend/functions/metrics/package.json
source/backend/functions/opensearch-setup/package-lock.json
source/backend/functions/opensearch-setup/package.json
source/backend/functions/search-api/package-lock.json
source/backend/functions/search-api/package.json
source/backend/functions/settings/package-lock.json
source/backend/functions/settings/package.json
source/frontend/package-lock.json
source/frontend/package.json
source/infrastructure/package-lock.json
source/sdk/js/package-lock.json

- Security [vulnerability](https://github.com/advisories/GHSA-2p57-rm9w-gvfp) in `ip`.
- Security [vulnerability](https://github.com/advisories/GHSA-grv7-fg5c-xmjg) in `braces`.

update to v2.1.8

---

docs/package-lock.json

update braces dep in docs folder

---

CHANGELOG.md
README.md
source/backend/discovery/Dockerfile
source/backend/discovery/package-lock.json
source/backend/discovery/package.json
source/backend/functions/account-import-templates-api/package-lock.json
source/backend/functions/account-import-templates-api/package.json
source/backend/functions/cost-parser/package-lock.json
source/backend/functions/cost-parser/package.json
source/backend/functions/cur-notification/package-lock.json
source/backend/functions/cur-notification/package.json
source/backend/functions/cur-setup/package-lock.json
source/backend/functions/cur-setup/package.json
source/backend/functions/graph-api/package-lock.json
source/backend/functions/graph-api/package.json
source/backend/functions/metrics/package-lock.json
source/backend/functions/metrics/package.json
source/backend/functions/opensearch-setup/package-lock.json
source/backend/functions/opensearch-setup/package.json
source/backend/functions/search-api/package-lock.json
source/backend/functions/search-api/package.json
source/backend/functions/settings/package-lock.json
source/backend/functions/settings/package.json
source/frontend/package-lock.json
source/frontend/package.json

- Use Amazon Linux 2023 as the base image for the discovery process Docker container

update to v2.1.11

---

CHANGELOG.md
README.md
source/backend/discovery/package-lock.json
source/backend/discovery/package.json
source/backend/functions/account-import-templates-api/package-lock.json
source/backend/functions/account-import-templates-api/package.json
source/backend/functions/cost-parser/package-lock.json
source/backend/functions/cost-parser/package.json
source/backend/functions/cur-notification/package-lock.json
source/backend/functions/cur-notification/package.json
source/backend/functions/cur-setup/package-lock.json
source/backend/functions/cur-setup/package.json
source/backend/functions/graph-api/package-lock.json
source/backend/functions/graph-api/package.json
source/backend/functions/metrics/package-lock.json
source/backend/functions/metrics/package.json
source/backend/functions/opensearch-setup/package-lock.json
source/backend/functions/opensearch-setup/package.json
source/backend/functions/search-api/package-lock.json
source/backend/functions/search-api/package.json
source/backend/functions/settings/package-lock.json
source/backend/functions/settings/package.json
source/frontend/package-lock.json
source/frontend/package.json

- Security [vulnerability](https://github.com/advisories/GHSA-8hc4-vh64-cxmj) in `axios`.

update to v2.1.13

---

CHANGELOG.md
README.md
source/backend/discovery/package-lock.json
source/backend/discovery/package.json
source/backend/functions/account-import-templates-api/package-lock.json
source/backend/functions/account-import-templates-api/package.json
source/backend/functions/cost-parser/package-lock.json
source/backend/functions/cost-parser/package.json
source/backend/functions/cur-notification/package-lock.json
source/backend/functions/cur-notification/package.json
source/backend/functions/cur-setup/package-lock.json
source/backend/functions/cur-setup/package.json
source/backend/functions/graph-api/package-lock.json
source/backend/functions/graph-api/package.json
source/backend/functions/metrics/package-lock.json
source/backend/functions/metrics/package.json
source/backend/functions/opensearch-setup/package-lock.json
source/backend/functions/opensearch-setup/package.json
source/backend/functions/search-api/package-lock.json
source/backend/functions/search-api/package.json
source/backend/functions/settings/package-lock.json
source/backend/functions/settings/package.json
source/cfn/templates/main.template
source/frontend/package-lock.json
source/frontend/package.json
source/frontend/vite.config.js
source/sdk/js/package-lock.json

- Cron expression for running discovery process every 24 hours. [546](https://github.com/aws-solutions/workload-discovery-on-aws/discussions/546)
- Security [vulnerability](https://github.com/advisories/GHSA-gcx4-mw62-g8wm) in `rollup`.
- Security [vulnerability](https://github.com/advisories/GHSA-9cwx-2883-4wfx) in `vite`.
- Security [vulnerability](https://github.com/advisories/GHSA-64vr-g452-qvp3) in `vite`.

update to v2.1.15
