source/backend/discovery/src/discovery/generateHeader.js
*Issue #:* #29 (partially)
Use resource name if available, fall back to ID.
Note: there's no tests, I'm not entirely sure if it works as expected, please check.
=> Show resource names instead of IDs

source/backend/discovery/buildspec.yml, source/cfn/templates/zoom-discovery-crawler.yaml
The discovery component runs in a docker base image that triggers ECR security warnings.
We're trying to build it on top of our pre-baked docker node12 base image that is updated regularly. I was trying to re-use the existing build pipeline and update `buildspec.yaml` and `Dockerfile`. I stumbled on 2 issues:
- build spec is hardcoded in CloudFormation templates. There's `source/backend/discovery/buildspec.yml` but it's not in use (maybe internally?)
- CodeBuild doesn't have permissions to pull from another ECR
With this PR the build pipeline for the discovery component should become more flexible and allow some customisation.
Summary of the changes:
- Move hardcoded `buildspec.yaml` from CloudFormation template to …
=> Enable buildspec.yaml customization

source/backend/discovery/src/lib/awsClient.js
The `describeContainerInstances` and `describeTasks` ECS APIs share the same throttling limits ([approx 20TPS](https://docs.aws.amazon.com/AmazonECS/latest/APIReference/request-throttling.html)). This was causing throttling issues for a customer with a large number of ECS tasks as we were not throttling `describeTasks`. We now split the TPS evenly between the two operations.
=> Ecs describe throttling

source/backend/discovery/src/lib/additionalResources/firstOrderHandlers.js, source/backend/discovery/test/additionalRelationships.js, source/backend/discovery/test/createAdditionalResources.js, source/backend/discovery/test/fixtures/additionalResources/apigateway/authorizerNoProvider.json
The code to create relationships for API Gateway authorizers assumes that the providerARNs field is always present. This is not the case so we now provide a fallback value of [] before mapping over it.
=> Null arn api gateway

source/backend/discovery/src/lib/additionalRelationships/createBatchedHandlers.js, source/backend/discovery/src/lib/additionalRelationships/createEnvironmentVariableRelationships.js, source/backend/discovery/src/lib/additionalRelationships/createIndividualHandlers.js, source/backend/discovery/src/lib/additionalRelationships/createLookUpMaps.js, source/backend/discovery/src/lib/additionalRelationships/index.js, source/backend/discovery/src/lib/utils.js, source/backend/discovery/test/apiClient/index.js, source/backend/discovery/test/apiClinet/index.js
The `createAdditionalRelationships` function was nearly one thousand lines long. This CR splits it up into modules in a similar way to the `sdkResources` functionality. There have been no changes to the code, it has just been moved to different files and all the unit tests passed. CRUX has tried to be smart and made a mess of the diff for the `createIndividualHandlers.js` file.
=> Split create additional relationships

source/backend/discovery/src/lib/additionalRelationships/addBatchedRelationships.js, source/backend/discovery/src/lib/additionalRelationships/index.js, source/backend/discovery/src/lib/constants.js
The logging when adding relationships that rely on list* APIs is very verbose (4 log statements per region per account). This CR consolidates the logging of errors into one place and makes it consistent with error logging in other parts of the application.
=> Reduce logging in addBatchedRelationships

source/backend/discovery/src/lib/additionalRelationships/addIndividualRelationships.js, source/backend/discovery/src/lib/additionalRelationships/index.js, source/backend/discovery/src/lib/index.js
This PR moves the concurrency control to the `addIndividualRelationships` function rather than having it in the main `addAdditionalRelationships` function, which makes it consistent with the batch handlers.
=> Make code that adds relationships individually consistent with batch handlers

.github/workflows/pipeline-workflow.yml
Removes Node 12 warning from pipeline workflow
=> use node 16 version aws credentials gh action

.idea/aws.xml, source/backend/discovery/src/lib/additionalRelationships/addBatchedRelationships.js, source/backend/discovery/src/lib/additionalRelationships/addIndividualRelationships.js, source/backend/discovery/src/lib/additionalRelationships/createEnvironmentVariableRelationships.js, source/backend/discovery/src/lib/additionalRelationships/createLookUpMaps.js, source/backend/discovery/test/additionalRelationships.js, source/backend/discovery/test/fixtures/relationships/cloudfront/distribution/s3.json, source/backend/discovery/test/fixtures/relationships/cloudfrontStreamingDistribution/s3.json
The discovery process uses a series of hash maps so that when creating relationships between  resources we can do look ups for specific resources in O(1) time rather than search the array (an O(n) operation) of resources we get from AWS Config. Over time, the function that creates these maps has become quite complex. 
This PR factors out some common logic when creating these hash maps into separate function, which allows us to reduce the number of cases in the `switch` statement. We also remove one of the maps (`s3ResourceIdToRegionMap`) entirely as we can use the the ARN of the S3 bucket to find it because we know they are globally unique.
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms …
=> Simplify creation of lookup maps for creating relationships

.idea/aws.xml, source/backend/discovery/src/lib/apiClient/appSync.js, source/backend/discovery/src/lib/persistence/transformers.js, source/backend/discovery/test/createResourceAndRelationshipDeltas.js, source/backend/graphql/schema/perspective-api.graphql, source/frontend/src/API/GraphQL/queries.js
Issue #, if available: 
Resolves #368
As described in the rationale in this issue linked above, there is no need to store the `relationships` field we retrieve from AWS Config. This change is mainly focused on the discovery process (although we also remove the field from the GraphQL schema), which was the only component that interacted with that field in the DB.
=> don't write relationships field from config to DBs

source/backend/discovery/src/lib/apiClient/appSync.js, source/backend/discovery/src/lib/apiClient/index.js, source/backend/discovery/src/lib/config.js, source/backend/discovery/src/lib/constants.js, source/backend/discovery/src/lib/index.js, source/backend/discovery/src/lib/intialisation.js, source/backend/discovery/src/lib/persistence/index.js, source/backend/discovery/test/initialisation.js, source/backend/functions/settings/src/index.js, source/backend/functions/settings/test/index.js, source/backend/graphql/schema/perspective-api.graphql, source/frontend/src/API/GraphQL/queries.js, source/frontend/src/components/RegionManagement/DiscoverableRegions/DiscoverableAccountsTable.js, source/frontend/src/components/RegionManagement/SinglePageImport/TemplateProvider.js, source/frontend/src/config/constants.js
Issue #, if available:
Closes #367. Completes #1.
This pull requests implements changes on the frontend to display to users if the global resources template has been deployed to accounts that have been added to Workload Discovery. This also required changes on that backend to catch failures when attempting to assume the IAM role provisioned by the global resources template and persist them in the database that stores accounts.
If the IAM role has not been deployed, the UI will present a warning with remediation steps. These steps will be different depending on whether the solution has been deployed with the AWS Organizations integration or not.
Self-managed Account Discovery:
AWS Organizations Account Discovery:
=> Record and display IAM errors when discovering accounts

source/frontend/src/components/Diagrams/Draw/Canvas/Export/JSON/CreateJSONExport.js
Issue #, if available:
Fixes #336 
The old implementation uses the canvas Cytoscape object directly to get the nodes and edges but now that processing is done before calling the export function.
=> Fix json export functionality

source/cfn/templates/main.template
This PR does some housekeeping for the main CloudFormation template. There was a mixture of single, double and (mainly) no quotes being used for strings. Now the template uses no quotes as the default with single quotes only where necessary (one exception is the regex CloudFormation condition that must be wrapped in double quotes). It also replaces the use of `!GetAtt` in string interpolation with `!Sub` to make it consistent with the rest of the template.
=> Tidy up main CloudFormation template

source/backend/functions/graph-api/package-lock.json, source/backend/functions/graph-api/package.json, source/backend/functions/graph-api/src/index.js, source/backend/functions/graph-api/test/index.js, source/backend/graphql/schema/perspective-api.graphql, source/cfn/templates/gremlin-resolvers.template
Issue #, if available:
Backend changes required for #378.
This PR adds a new GraphQL query that takes a list of resource IDs and queries the Neptune database to find the first order relationships and second order networking relationships (subnets and VPCs only). It returns the result of this query as a list of nodes and another list of the edges between them. [Caching on the Gremlin query](https://docs.aws.amazon.com/neptune/latest/userguide/gremlin-results-cache.html) is also enabled on the to allow for pagination, a key requirement to solve #351.
=> add getResourceGraph gql query

.github/workflows/pull-request-workflow.yml, deployment/run-unit-tests.sh, source/backend/discovery/src/lib/intialisation.js, source/backend/discovery/test/apiClient/index.js, source/backend/discovery/test/initialisation.js, source/backend/discovery/test/persistence/transformers.js
The script that runs all the unit tests didn't have the `-e` flag set, so only failed if the last test suite that ran failed. Several unit tests were silently failing as a result and have now been fixed.
=> fix unit tests on ci

source/frontend/src/components/Diagrams/Draw/DrawDiagram/DiagramControlsPanel.js
There was a typo in the variable name that holds the date interval value when load costs onto the diagram. This meant that the default interval (five days) was always used.
=> Fix Load Costs date interval issue

source/backend/functions/graph-api/package-lock.json, source/backend/functions/graph-api/src/index.js, source/backend/functions/graph-api/test/index.js
Previously, the pagination parameter was being ignored in the Gremlin lambda resolver function. It will now apply to both the `nodes` and `edges` fields returned. When both fields return an empty array then the client will know the pagination has completed.
=> Add pagination to getResourcesGraph

source/backend/discovery/src/lib/additionalRelationships/addIndividualRelationships.js, source/backend/discovery/src/lib/awsClient.js, source/backend/discovery/src/lib/intialisation.js, source/backend/discovery/src/lib/sdkResources/createAllBatchResources.js, source/backend/discovery/src/lib/sdkResources/firstOrderHandlers.js, source/backend/discovery/src/lib/sdkResources/secondOrderHandlers.js, source/backend/discovery/src/lib/utils.js, source/backend/discovery/test/getAllSdkResources.js
When creating instances of an SDK client for a particular region, we were creating a throttler on instantiation. This meant that if we have several instances of the same client for a region they would all be using different throttlers. For throttling to work, all instances of the client must share the same throttler so the number of requests stays below the limits we've set. This change, creates a function that creates throttlers but is memoized so that if a client is instantiated with the same name, credentials, region and throttling parameters that it will return a previously created throttling instance (should it exist).
=> Memoize throttler creation

source/backend/discovery/src/lib/aggregator/getAllConfigResources.js
AWS Config announced support for EFS resource types from the Advanced Query API, we no longer need to retrieve these types from the `ListAggregateDiscoveredResources` API now.
=> Get EFS resources from Advanced Query API

source/backend/discovery/src/lib/additionalRelationships/addIndividualRelationships.js, source/backend/discovery/src/lib/sdkResources/firstOrderHandlers.js, source/backend/discovery/test/getAllSdkResources.js
The field containing the DynamoDb Stream ARN returned by the `describeStream` is `StreamArn` not `StreamARN`. This fixes the null value that was being used for the resource types ARN.
=> fix dynamodb stream ARN field casing

source/backend/functions/search-api/package-lock.json, source/backend/functions/search-api/package.json, source/backend/functions/search-api/src/index.js
The search API lambda was the last GraphQL resolver that was using the old AWS JS SDK. This PR updates it to v3.
=> update search api to use v3 of the aws sdk
